
name: flutter_back4app_app
description: A Flutter app using Back4App for authentication and CRUD.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  parse_server_sdk_flutter: ^5.1.0

flutter:
  uses-material-design: true
